### ISSUE TITLE
Function Does Not Appear In AWS Console

### ISSUE THREAD

**Issue by JimLynchCodes** [nervous-systems/cljs-lambda#100]
Should I be able to see the successfully deployed function in AWS console as "work magic"? I can deploy and invoke the function, but I see no trace of it in the console.

**Comment by moea** [comment]
The region you have selected in the console is probably different to the region you deployed to.

http://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/getting-started.html#select-region

The function deploys by default to us-east-1, unless you specified another region in project.clj or when running aws configure.

**Comment by JimLynchCodes** [comment]
doh, I was looking at the wrong region. Ok, I think I'm ready to have a go at writing my own clojurescript lambda functions now. Thanks a lot for you help!
