### ISSUE TITLE
Strategy for keywordizing keys and values?

### ISSUE THREAD

**Issue by grav** [nervous-systems/cljs-lambda#101]
Hi! What's the strategy for keywordizing keys and values?
If I invoke with eg
`lein cljs-lambda invoke myFn '{"foo":"bar"}',`,
 it arrives in my `deflambda` as `{:foo :bar}`.

This seems a bit too magical to me, as I might want `{"foo" "bar"}`, `{:foo "bar"}` or maybe even `{"foo" :bar}`. It probably should be up to the implementer.

**Comment by moea** [comment]
You shouldn't get `{:foo :bar}`, rather `{:foo "bar"}` - see https://github.com/nervous-systems/cljs-lambda/blob/master/cljs-lambda/src/cljs_lambda/util.cljs#L25

Are you sure the value is a keyword?  

In any case, you can avoid all of this behaviour by using `cljs-lambda.util/async-lambda-fn` directly:

```clojure
(def ^:export my-fn
  (async-lambda-fn
    (fn [event ctx]
      ...)
    {:parse-input? false}))
```

In the above, `event` is a vanilla Javascript object, not a cljs map.

**Comment by grav** [comment]
@moea You're right, the value is a string, sorry, my mistake.
Great tip regarding the async function, thanks for the pointer.

And thanks for a cool project :-)
