### ISSUE TITLE
How To Return JSON?

### ISSUE THREAD

**Issue by JimLynchCodes** [nervous-systems/cljs-lambda#102]
Hey, thanks again for making this. I'm wordering how to return normal JSON as my response seems to always look like a Clojure map even when I return `(js-obj "a" 1 "b" true "c" "hello there, caller!")` or `#js{:a 1, :b true, :c nil}`.

**Comment by moea** [comment]
@JimTheMan Whatever you return is serialised to JSON.  If you're invoking your function with `lein cljs-lambda invoke`, it prints Clojure data because that's what the JSON is parsed into.  Try invoking your function directly with the AWS CLI or from the AWS console to see the raw output.

**Comment by JimLynchCodes** [comment]
oh, nice. haha thanks!
