### ISSUE TITLE
Weird Response In Lambda Console

### ISSUE THREAD

**Issue by JimLynchCodes** [nervous-systems/cljs-lambda#106]
Hi, I'm getting very odd-looking responses in the AWS Lambda console. 

I can see things happening in the cloudwatch logs so I know this bit of code is being executed:

`(ctx/succeed! ctx "Derp")`

But it seems like I can't send a string, mmap, js object...

In the AWS console my response always looks like this:

>     "tail": 0,
>     "length": 0,
>     "arr": [
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null
>     ]
>   },
>   "dirty_takes": 0,
>   "puts": {
>     "head": 0,
>     "tail": 0,
>     "length": 0,
>     "arr": [
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null
>     ]
>   },
>   "dirty_puts": 0,
>   "buf": {
>     "buf": {
>       "head": 0,
>       "tail": 0,
>       "length": 0,
>       "arr": [
>         null
>       ]
>     },
>     "n": 1,
>     "cljs$lang$protocol_mask$partition0$": 2,
>     "cljs$lang$protocol_mask$partition1$": 0
>   },
>   "closed": false
> }
>

**Comment by JimLynchCodes** [comment]
If you can, please check this project which is basically all contained in this one file: https://github.com/JimTheMan/Cljs-Twitter-Unfollower/blob/master/twitter-unfollower/src/twitter_unfollower/core.cljs

**Comment by moea** [comment]
@JimTheMan sorry for the late response.  The channel returned by your lambda function has a channel on it, because you aren't taking (w/ `<!`) from the result of the call to `unfollowUser`.  The data structure in your issue is the JSON representation of a core.async channel.

**Comment by JimLynchCodes** [comment]
Thanks Moe! I figured it was trying to log the channel itself. I'm still not totally understanding why the unfollowUser function returns a channel, but you are right that with a "<!" [here](https://github.com/JimTheMan/Cljs-Twitter-Unfollower/blob/master/twitter-unfollower/src/twitter_unfollower/core.cljs#L82) it works! thanks again. :)
