### ISSUE TITLE
Add version to lambda function name

### ISSUE THREAD

**Issue by vorakumar** [nervous-systems/cljs-lambda#11]
Is there any way I can dynamically change the lambda name (specified in project.clj) to include version/ build number?

**Comment by moea** [comment]
There isn't a cljs-lambda specific solution, but as far as Leiningen goes, I think you could do something like:

``` clojure
{...
  :functions
  [{:name   ~(str "topic-to-queue-" (System/getenv "TOPIC_TO_QUEUE_VERSION"))
    :invoke  chemtrack.lambda/topic-to-queue
    :timeout 20}]}
```

Or similar.  You can obviously evaluate whatever expression you like, to derive the version.  Is that helpful?

**Comment by vorakumar** [comment]
Yeah, I realized that after I posted the question. Thanks for the quick response! So far, this is working out well for our project. :+1:

**Comment by moea** [comment]
Great! Let me know if you run into anything else.
