### ISSUE TITLE
Example with dynamodb

### ISSUE THREAD

**Issue by ulsa** [nervous-systems/cljs-lambda#2]
It would be enlightening to see how to idiomatically use `async-lambda-fn` together with external calls, for example to dynamodb. The callbacks there return either an Error or the result. I'm sure channels can be used to an advantage here, but I'll need an example to really grasp it.

**Comment by moea** [comment]
Ulrik,

https://github.com/nervous-systems/chemtrack-example has a Lambda function in it which uses SQS/SNS, and is covered [in this blog post](https://nervous.io/clojure/clojurescript/node/aws/2015/08/09/chemtrails/).  The library used has the same error behaviour as e.g. Hildebrand.

That said, error handling was omitted to avoid complicating the example, though there are examples in the Hildebrand code - [it's something like this](https://github.com/nervous-systems/hildebrand/blob/c9a6d44c6e5319f2287616a0ec81cf797eaa795c/src/hildebrand/core.cljc#L60).  [glossop](https://github.com/nervous-systems/glossop), the project which contains `<?` and `go-catching` is undocumented, though they're pretty simple macros.  I should get around to at least writing a readme.

**Comment by ulsa** [comment]
That's great. Thanks. 

Here's the clueless stuff that I came up with on my own:

``` clojure
(ns rps.core
  (:require [rps.game-store :as game-store]
            [cljs-lambda.util :refer [async-lambda-fn]]
            [cljs.core.async :refer [<!]])
  (:require-macros [cljs.core.async.macros :refer [go]]))

(def ^:export create-game
  (async-lambda-fn
    (fn [{:keys [email] :as event} context]
      (go
        (println "input event:" (pr-str event))
        (let [res (<! (game-store/create-game (str (random-uuid)) email))]
          (if (instance? js/Error res)
            (println "error:" (pr-str (js->clj res))) ; not sure if this will work
            (println "result:" (pr-str res)))
          res)))))
```

``` clojure
(ns rps.game-store
  (:require [cljs.nodejs :as node]
            [cljs.core.async :refer [chan put!]]))

(defn create-game [game-id email]
  (let [c (chan)
        db (aws.DynamoDB.)]
    (.putItem db (clj->js {:Item      {:gameId  {:S game-id}
                                       :state   {:S :created}
                                       :player1 {:S email}}
                           :TableName :rpslab-games})
      (fn [err data]
        (if err
          (put! c err)
          (put! c {:gameId game-id}))))
    c))
```

**Comment by moea** [comment]
Yeah, that's basically what's happening with <? and go-catching.  For better or worse, I generally use go-catching _everywhere_ (which terminates the go block on error, but places the error itself on the channel - it's what you're doing in create-game, essentially) - to emulate blowing the stack, since for a lot of errors (e.g. provisioned throughput exceeded, in a case like this) much of the application has no idea what to do.

[There's a brief disussion of errors in this Dynamo/Hildebrand blog post](https://nervous.io/clojure/aws/dynamo/hildebrand/2015/06/01/hildebrand/#errors).
