### ISSUE TITLE
using lambda role in sns/publish-topic!

### ISSUE THREAD

**Issue by keeth** [nervous-systems/cljs-lambda#3]
Hello,

I'm trying to make a lambda endpoint that sends messages to SNS...

```
(ns parsehook.core
  (:require [cljs-lambda.util :refer [async-lambda-fn]]
            [fink-nottle.sns :as sns]
            [cljs.core.async :refer [chan <!]]
            [eulalie.instance-data :refer [default-iam-credentials!]])
  (:require-macros [cljs.core.async.macros :refer [go]]))

(def ^:export work-magic
  (async-lambda-fn
   (fn [event context]
     (go
       (<! (sns/publish-topic!
             (<! (default-iam-credentials!))
             "arn:aws:sns:us-west-2:785400771354:parsehook-qa"
             (.stringify js/JSON event)))))))

```

does the above usage of default-iam-credentials look correct?  When I do it this way and invoke the function I get:

`{:errorMessage "Task timed out after 3.00 seconds"}`

When i pass creds as a regular map with {:access-key, :secret-key and :region} it works.  But I'd prefer to use the IAM role if possible.  Not sure if my script is throwing an exception when I try to use (default-iam-credentials!)... I'm unclear how error reporting works in Lambda, beyond returning an Error via the channel.

I am not in the default region, not sure if I need to assoc region into the default-iam-credential or something.  I'm totally new to lambda, just trying to figure it out.  Thanks!

**Comment by moea** [comment]
I think the point you're raising about whether `default-iam-credentials!` ought to be able to auto-retrieve the correct region from the instance metadata is a good one - though I'm not sure that's what's operative here.

If this function is running on the Lambda infrastructure, environment variables are used to convey the appropriate function role - a map containing these can be retrieved via `eulalie.creds/env` - which just returns the map, not a channel, so something like:

``` clojure
(sns/publish-topic!
  (eulalie.creds/env)
  "arn:aws:sns:us-west-2:785400771354:parsehook-qa"
  (.stringify js/JSON event))
```

Ought to work.  It sounds like you may want to do something else to communicate the region (and then assoc it onto the map returned by (env)), and I'm not sure the Lambda infrastructure facilitates this.  Let me know if you think there's a way to make that bit easier.

N.B. Returning an error via async-lambda-fn's channel _is_ how errors are reported, though they may be swallowed (or obscured, at best) with nested async calls - `<?` and `go-catching` (or just using `<?` + `(go (try ...))`) from https://github.com/nervous-systems/glossop may help with that - it's a transitive dep of your project already.  There are examples of using it throughout eulalie and fink-nottle.

**Comment by keeth** [comment]
Got it working, thanks!  Here's the working snippet:

```
(def ^:export publish-to-sns
  (async-lambda-fn
   (fn [event context]
     (go-catching
       (<! (sns/publish-topic!
             (assoc (eulalie.creds/env) :region "us-west-2")
             "arn:aws:sns:us-west-2:785400771354:parsehook-qa"
             (.stringify js/JSON (clj->js event))))))))
```
