### ISSUE TITLE
Publishing & aliasing multiple functions

### ISSUE THREAD

**Issue by zrzka** [nervous-systems/cljs-lambda#38]
It's a pain to :publish & :alias lot of functions (same for all of them, like build-XX where XX is Travis build number for example) without additional scripting. Is anyone working on this? If not, I need it and I would like to help with this feature if you're interested.

**Comment by moea** [comment]
I'm not working on it - one thing I was going to work on was the ability to update an existing alias (like `:alias xxx :update`).  I explicitly disabled multi-function publish/alias, but I agree it wasn't the best idea - feel free to knock it out.

**Comment by zrzka** [comment]
Great, I'll do it next week after our internal release.
