### ISSUE TITLE
clojure.pprint not found (Travis CI)

### ISSUE THREAD

**Issue by zrzka** [nervous-systems/cljs-lambda#42]
Travis CI did update images today. Didn't find time to investigate this issue yet, maybe something will come to your mind immediately when you see it. There's this error when `deploy` is called:

```
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: clojure.pprint, compiling:(leiningen/cljs_lambda/aws.clj:181:7)
```

Will check what's wrong tomorrow.

**Comment by moea** [comment]
`aws.clj` uses that namespace, but doesn't require it - it's likely that this issue would depend on the version of Leiningen which is running, or some other thing we shouldn't be counting on.  In either case, I'll push 0.6.2-SNAPSHOT in a moment w/ a fix for this.

**Comment by moea** [comment]
Pushed

**Comment by zrzka** [comment]
You're fast :-) Just woke up, changed version to 0.6.2-SNAPSHOT and it works again. Thanks.

<img width="517" alt="screen shot 2016-08-25 at 7 56 52" src="https://cloud.githubusercontent.com/assets/1084172/17958375/9f61adec-6a99-11e6-8717-71e711f75362.png">

**Comment by zrzka** [comment]
Tested several times, several repos, just works. Feel free to close this issue if you're not planning to do more work on this.

**Comment by moea** [comment]
I'll wait until I've promoted the snapshot to a release, otherwise I'm likely to forget to do it.
