### ISSUE TITLE
Throw error if npm is not installed

### ISSUE THREAD

**Issue by jellea** [nervous-systems/cljs-lambda#52]
First of all! Great work! Just deployed my first lambda function! 

Not having npm in my path on shell load causes `lein cljs-lambda deploy` to silently fail, maybe an error would be great? I just lost half an hour because of this as I didn't expect node to be involved with deploying.

**Comment by moea** [comment]
@jellea Thanks for reporting, and glad your deploy (eventually) worked out.  I think this issue may fall within the purview of `lein-npm`, which is handling all of the `node`/`npm` interaction.  I can check whether we're swallowing any log messages, but checking for the existence of a Node executable seems like it may be something `lein-npm` ought to doing.
