### ISSUE TITLE
Transition to using Node v4.3 callback param

### ISSUE THREAD

**Issue by leppert** [nervous-systems/cljs-lambda#54]
From the [AWS docs](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html#transition-to-new-nodejs-runtime):

> If you previously created Lambda functions using Node.js runtime v0.10.42, you used one of the context object methods (done(), succeed(), and fail()) to terminate your Lambda function. In Node.js runtime v4.3, these methods are supported primarily for backward compatibility. We recommend you use the callback (see Using the Callback Parameter).

There's more on their reasoning in [the announcement](https://aws.amazon.com/blogs/compute/node-js-4-3-2-runtime-now-available-on-lambda/).

**Comment by moea** [comment]
The callback parameter is now used if available at runtime.
