### ISSUE TITLE
Without advanced optimizations, deploys non-working function

### ISSUE THREAD

**Issue by glv** [nervous-systems/cljs-lambda#55]
I'm working on a function that will depend on a node.js package. Guided by [the comment here](https://github.com/clojure/clojurescript/wiki/Quick-Start#running-clojurescript-on-nodejs):

> Note: Under Node.js there is little reason to use advanced optimizations. While advanced optimizations does apply performance related optimizations, these are now largely obviated by optimizations present in modern JavaScript virtual machines like V8, SpiderMonkey, and JavaScriptCore. For Node.js, :simple or :none optimizations suffice and using them removes the need for extra steps like supplying an externs file.

I decided to try deploying the cljs-lambda example function using `:simple` optiimizations.  But the deployed function fails.  (It took me a while to figure out the nature of the failure, but `base.js` is apparently attempting to load a non-existent `deps.js` file.)

**Comment by moea** [comment]
@glv The cljs compiler outputs a very different directory/path structure depending on the optimisation level.  I personally only ever use `:none` or `:advanced`, as does the related template - so if this issue isn't a regression specific to compiler versions (what version of cljs are you using?), then it could potentially be of long standing, but likely isn't super difficult to fix.  Please let me know if `:none` works for you, and I'll take a look at what needs to be done to support  `:simple`.

I'm not recommending advanced over none (I mostly use the latter), but a counterpoint to the quoted paragraph is that without advanced dead-code elimination, the transfer portion of deploys is likely to be slower, and the startup time (which is obviously pretty important) may be affected - but I have absolutely no data to support this, and suspect that differences in startup time won't be dramatic in most instances.

**Comment by moea** [comment]
There's a multimethod [here](https://github.com/nervous-systems/cljs-lambda/blob/master/plugin/src/leiningen/cljs_lambda/zip_tedium.clj#L51) which dispatches on the optimization level.  If you're motivated to fix this, and get to it before I do, arranging the zip differently in a `:simple` method would be the approach.

P.S. As much of your project file as you're comfortable posting (deps, cljsbuild) would be helpful.

**Comment by glv** [comment]
Thanks, this is helpful. I'll take a crack at it and see what I can learn. :-)

**Comment by moea** [comment]
@glv io.nervous/lein-cljs-lambda 0.6.5-SNAPSHOT includes provisional support for :optimizations :simple.  [The changes are here](https://github.com/nervous-systems/cljs-lambda/commit/de159ea90f84030bf99c7fa19d57ac39e1a2c23d).  I haven't regression tested or anything, but it appears to work for a non-trivial example.

**Comment by moea** [comment]
Closing, as 0.6.5 appears to be working fine w/ `:simple`
