### ISSUE TITLE
Add example of how to set a region in project.clj

### ISSUE THREAD

**Issue by danielcompton** [nervous-systems/cljs-lambda#7]
I've tried `:region` in `[:cljs-lambda :defaults]`, and in `[:cljs-lambda]` and they both don't seem to be using the supplied region, and are instead taking the one from my profile. Should I be putting it somewhere else?

**Comment by moea** [comment]
This isn't currently a feature - more than happy to accept a PR, else I'll be able to get it to over the next week or so.

**Comment by moea** [comment]
Daniel - sorry, this took a while.  0.3.1-SNAPSHOT of the plugin contains this feature, and it's documented [here](https://github.com/nervous-systems/cljs-lambda/blob/extended-cmd-line/README.md), for now.  Will close the issue on release.

**Comment by moea** [comment]
0.4.0
