### ISSUE TITLE
ReferenceError when using :cljs-lambda {:compiler ...} and :optimizations :advanced

### ISSUE THREAD

**Issue by alessandrod** [nervous-systems/cljs-lambda#78]
Here's a better description of the ReferenceError bug I tried to fix as part of #77.

To reproduce the bug, create a new project with the serverless-cljs template, then change :optimizations to :advanced and finally try to run the output: you get the ReferenceError.

The serverless-cljs template creates the following project.clj:

    (defproject bar "0.1.0-SNAPSHOT"
    :dependencies [[org.clojure/clojure       "1.8.0"]
                    [org.clojure/clojurescript "1.8.51"]
                    [io.nervous/cljs-lambda    "0.3.5"]]
    :plugins [[lein-npm                    "0.6.2"]
                [io.nervous/lein-cljs-lambda "0.6.5"]]
    :npm {:dependencies [[serverless-cljs-plugin "0.1.2"]]}
    :cljs-lambda {:compiler
                    {:inputs  ["src"]
                    :options {:output-to     "target/bar/bar.js"
                            :output-dir    "target/bar"
                            :target        :nodejs
                            :language-in   :ecmascript5
                            :optimizations :advanced}}})

As you can see it uses :cljs-lambda {:compiler ...} to configure the compiler instead of specifying a :cljsbuild key. That leads lein-cljs-lambda to invoking the clojurescript compiler directly instead of going through cljsbuild, which ultimately causes this issue.

Below is a transcript of how I can reproduce the bug:

    Script started on Wed May  3 20:05:34 2017
    alessandro@june:/tmp$ lein new serverless-cljs bar
    Generating fresh 'lein new' serverless-cljs project.
    alessandro@june:/tmp$ cd bar/
    alessandro@june:/tmp/bar$ sed -i -e s/:none/:advanced/ project.clj 
    alessandro@june:/tmp/bar$ grep optimizations project.clj 
                            :optimizations :advanced}}})
    alessandro@june:/tmp/bar$ lein deps
    bar@0.1.0-SNAPSHOT /private/tmp/bar
    └─┬ serverless-cljs-plugin@0.1.2 
    ├── bluebird@3.4.6 
    ├── lodash@4.17.2 
    └─┬ mkdirp@0.5.1 
        └── minimist@0.0.8 

    alessandro@june:/tmp/bar$ serverless package
    Serverless: Targeting /private/tmp/bar/.serverless/bar.zip
    Serverless: Packaging service...
    Serverless: Executing "lein update-in :cljs-lambda assoc :functions '[{:name "bar-dev-echo" :invoke bar.core/echo}]' -- cljs-lambda build :output /private/tmp/bar/.serverless/bar.zip :quiet"
    Serverless: Returning artifact path /private/tmp/bar/.serverless/bar.zip[39m
    alessandro@june:/tmp/bar$ unzip -q -d aws_zip .serverless/bar.zip 
    alessandro@june:/tmp/bar$ cd aws_zip
    alessandro@june:/tmp/bar/aws_zip$ cat index.js 

    require("./target/bar/bar.js");

    exports.bar_core_SLASH_echo = bar.core.echo;

    alessandro@june:/tmp/bar/aws_zip$ node index.js 
    /private/tmp/bar/aws_zip/index.js:4
    exports.bar_core_SLASH_echo = bar.core.echo;
                                ^

    ReferenceError: bar is not defined
        at Object.<anonymous> (/private/tmp/bar/aws_zip/index.js:4:31)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:423:7)
        at startup (bootstrap_node.js:147:9)
        at bootstrap_node.js:538:3
    alessandro@june:/tmp/bar/aws_zip$ exit
    exit

    Script done on Wed May  3 20:08:35 2017

**Comment by moea** [comment]
0.6.6-SNAPSHOT updated, will close on release.

**Comment by alessandrod** [comment]
Thanks a lot :)

Also don't forget to merge a7157717c8251b74495d7026d10e2f2784b5578f (the template revert) to master please.
