### ISSUE TITLE
Can't use mock-context on a REPL

### ISSUE THREAD

**Issue by asrail** [nervous-systems/cljs-lambda#9]
While using this in ClojureScript:
`(:require      [cljs-lambda.util :refer [mock-context]])`

I can use mock-context and it is `#<function cljs_lambda$util$mock_context(){...`

While on a ClojureScript REPL, using the same require, mock-context is always nil. I have tried both Rhino and Node.js REPLs. I can import and use async-lambda-fn, for instance, but not mock-context.

Simple that require line above followed by `(mock-context)` will raise an error, because mock-context is nil.

**Comment by asrail** [comment]
OK, I found out the issue. I was using 0.0-338 and the issue that I described happens there. I've just upgraded to 1.7.228 and the issue is simple solved.

**Comment by moea** [comment]
It's a new feature - let me know if you run into any other issues.
