### ISSUE TITLE
Does the serverless support imply support for e.g. GCP Functions, Azure Cloud Functions?

### ISSUE THREAD

**Issue by lvh** [nervous-systems/cljs-lambda#95]
I haven't used the Serverless framework before, but my understanding is that one of it's biggest selling points is abstracting away the differences between GCP Functions, Azure Cloud Functions and AWS Lambda, making it possible to run almost the same codebase across different providers. Does that apply to projects made with this template too? Am I misunderstanding what Serverless provides, or what portions of it this project uses? (Is it just for uploading to AWS Lambda?)

**Comment by moea** [comment]
@lvh When a project is created with the `serverless-cljs` template and deployed via `serverless deploy`, serverless is 100% responsible for the upload/deployment portion. However, as the zip file of compiled javascript is opaque to it, I'd imagine there are differences in the runtime contract (i.e. the details of completion signalling, return type handling, handler argument types) which will affect whether code written for Lambda runs unmodified on those platforms.  

So, serverless may successfully abstract away the _deployment_ differences between those platforms, but the runtime differences will be present in the code. 

Assuming that for other platforms, serverless correctly handles the association of deployed function names with functions in your project, you can just list functions in serverless.yml that are defined in your project as `(defn ^:export my-handler [...] ....)` - i.e. not use any of the cljs-lambda stuff (deflambda, etc.) at _runtime_, just regular cljs functions - you'll have to come up with your own way of indicating completion to the caller, parsing the arguments, etc. - but cljs-lambda won't get in your way, once your function has started running (there's no need to depend on `cljs-lambda` the runtime library, if running outside of Lambda - `lein-cljs-lambda` will be used to build your code, but it doesn't generate anything Lambda specific).

**Comment by lvh** [comment]
That makes a lot more sense. Thanks @moea !
