### ISSUE TITLE
Use deflambda and defgateway docstring for lambda description

### ISSUE THREAD

**Issue by arichiardi** [nervous-systems/cljs-lambda#96]
Hi again!

This is a small improvement and feature request I noticed would be awesome.
The docstring can be used for the AWS Lambda description.

At the moment they are empty (I am using `serverless-cljs-plugin`).

Thanks as usual for your work and this plugin ;)

**Comment by moea** [comment]
@arichiardi Hi!

I considered this early on, but it's not generally possible.  No code in the project is evaluated by cljs-lambda as part of the build/deploy process, so it's not practical to read metadata from the handler vars - code only runs when the function is executed on AWS. 

 If this was something you really wanted, it would be possible to write a separate tool which loaded the code locally and remotely updated the descriptions.

**Comment by arichiardi** [comment]
Oh I see, that would have been possible during compilation only. Maybe a file containing `edn` that the `deploy` can read and that contains some info? Not a big deal, and I prefer to contribute other things, just brainstorming :wink:

**Comment by moea** [comment]
@arichiardi You can supply :description in the function's configuration map in project.clj - this could be read from a file if desired, e.g. `:description ~(slurp "my-description")` or something similar.  That's about as close as allowed with current functionality.

**Comment by arichiardi** [comment]
Right that's a good idea :wink: Did you have it or did I? :smile:

**Comment by moea** [comment]
😆
